import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/Components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 w-full bg-white shadow-md z-50 ">
          <Navbar />
        </nav>
        <div>
          <main className="pt-16">{children}</main>
        </div>
      </body>
    </html>
  );
}
